remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-remote-theme

title: "Tariere A. Timitimi"
description: "Data Science & ML/AI Portfolio"

# Required for version 6.x
footer-social-links:
  email: "tarieretimitimi@gmail.com"
  linkedin: "tariere-timitimi"
  github: "tarieret"
